# Generated by Django 3.1 on 2020-08-18 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[(None, 'Select Class'), ('Baby class', 'Baby class'), ('Class 1', 'class 1'), ('Class 2', 'class 2'), ('Class 3', 'class 3'), ('Class 4', 'class 4'), ('Class 5', 'class 5'), ('Class 6', 'class 6'), ('Class 7', 'class 7')], max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('Phase 1', 'Phase 1'), ('Phase 2', 'Phase 2'), ('Phase 3', 'Phase 3'), ('Phase 4', 'Phase 4')], max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('gender', models.CharField(blank=True, choices=[(None, 'Choose gender'), ('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('profile_pic', models.ImageField(default='default.png', upload_to='profile_pics')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='website.classroom')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_fees', models.FloatField(default=1000000)),
                ('paid_fees', models.FloatField()),
                ('remaining_fees', models.FloatField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.classroom')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.phase')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='website.student')),
            ],
        ),
    ]
