# Generated by Django 3.1 on 2020-11-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201129_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reports',
            field=models.FileField(blank=True, upload_to='reports'),
        ),
        migrations.AlterField(
            model_name='student',
            name='results',
            field=models.FileField(blank=True, upload_to='results'),
        ),
    ]
