# Generated by Django 3.1 on 2020-12-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_teacher_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='profile_pic',
            new_name='image',
        ),
    ]
