# Generated by Django 3.1 on 2020-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_teacher_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='/media/profile_pics/glogo.png', upload_to=''),
        ),
    ]
