# Generated by Django 3.1 on 2020-12-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20201202_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='/profile_pics/glogo.png', null=True, upload_to=''),
        ),
    ]
