# Generated by Django 3.1 on 2020-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20201207_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
