# Generated by Django 3.1 on 2020-12-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20201207_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
