# Generated by Django 3.1 on 2020-12-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20201207_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.BooleanField(blank=True, choices=[(None, 'Select status'), ('Passed', 'Passed'), ('Failed', 'Failed')], max_length=50, null=True),
        ),
    ]
