# Generated by Django 3.1 on 2020-12-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0024_auto_20201207_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjectcombination',
            name='select_class',
        ),
        migrations.RemoveField(
            model_name='subjectcombination',
            name='select_subject',
        ),
        migrations.AlterField(
            model_name='result',
            name='subject',
            field=models.CharField(blank=True, choices=[(None, 'Select subjects'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Swahili', 'Swahili'), ('Science', 'Science'), ('Sports', 'Sports')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='SubjectCombination',
        ),
    ]
